# Generated by Django 4.0 on 2023-03-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_orderitem__id_remove_shippingaddress__id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, default='products/default-image.png', upload_to='products/'),
        ),
    ]
