# Generated by Django 4.0 on 2023-03-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_discount_alter_product_hasdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hasDiscount',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
