# Generated by Django 4.0 on 2023-03-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_hasdiscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hasDiscount',
        ),
    ]
