# Generated by Django 4.0 on 2023-03-29 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_order_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default='dac57a90-78fe-42c1-a18b-a86ba792b8be', on_delete=django.db.models.deletion.CASCADE, to='core.customuser'),
            preserve_default=False,
        ),
    ]
