# Generated by Django 4.0 on 2023-04-18 13:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_adminmessage_remove_message_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.TextField(default='adsfadsf', max_length=450),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(default='dac57a90-78fe-42c1-a18b-a86ba792b8be', on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='core.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default='2e633b9f-718f-4fdc-8eca-9b8d907567ed', on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='core.customuser'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default='2e633b9f-718f-4fdc-8eca-9b8d907567ed', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='core.customuser'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdminMessage',
        ),
    ]
