# Generated by Django 4.0 on 2023-04-20 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_message_body_remove_message_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
