from django.urls import path
from core.views import product_views


urlpatterns = [
    path('', product_views.ProductListView.as_view(), name='product-list'),
    path('popular-products', product_views.PopularProductsListView.as_view(),
         name='popular-products'),
    path('product-suggestion/<str:pk>',
         product_views.ProductSuggestions.as_view(), name='product-suggestion'),
    path('new-products', product_views.NewProductsListView.as_view(),
         name='new-products'),
    path('sub-categories', product_views.SubCategoryListView.as_view(),
         name='sub-category-list'),
    path('categories', product_views.CategoryListView.as_view(),
         name='category-list'),
    path('create-review/<str:product_id>',
         product_views.review_create, name='create-review'),
    path('create-product', product_views.ProductCreateView.as_view(),
         name='create-product'),
    path('brands', product_views.BrandListView.as_view(), name='brand-list'),
    path('product-edit/<str:pk>',
         product_views.ProductEditView.as_view(), name='product-edit'),
    path('product-image-delete/<str:pk>',
         product_views.delete_product_images, name='product-image-delete'),
    path('get-total-annual-orders', product_views.get_total_annual_orders,
         name='get-total-annual-orders'),
    path('get-total-monthly-orders', product_views.get_total_monthly_orders,
         name='get-total-monthly-orders'),
    path('get-total-monthly-earnings',
         product_views.get_total_monthly_earnings, name='get-total-monthly-earnings'),
    path('get-total-annual-earnings',
         product_views.get_total_annual_earnings, name='get-total-annual-earnings'),
    path('get-monthly-earnings-by-days', product_views.get_monthly_earnings_by_days,
         name='get-monthly-earnings-by-days'),
    path('get-annual-earnings-by-months', product_views.get_annual_earnings_by_months,
         name='get-annual-earnings-by-months'),
    path('get-total-earnings-by-subCategory', product_views.get_total_earnings_by_subCategory,
         name='get-total-earnings-by-subCategory'),
    path('get-total-earnings-by-category', product_views.get_total_earnings_by_category,
         name='get-total-earnings-by-category'),
    path('get-total-earnings-by-country', product_views.get_total_earnings_by_country,
         name='get-total-earnings-by-country'),
    path('get-all-pending-requests', product_views.get_all_pending_requests,
         name='get-all-pending-requests'),
    path('<str:pk>', product_views.ProductDetailView.as_view(),
         name='product-detail'),
]
